### ISSUE TITLE
default boilerplate configuration

### ISSUE THREAD

**Issue by kumosal** [nswdpc/silverstripe-content-boilerplate#2]
Hello,

Thanks for this recipe. Could you explain how can I use the default boilerplate configuration? 
Should I copy it's content to: app/_config/_config.yml ?

Thanks

**Comment by JamesDPC** [comment]
Hi

Thanks for raising an issue. This module isn't a Silverstripe recipe, we've classed it as a `silverstripe-vendormodule` so when you install it, all the requirements will be installed and the [configuration](https://github.com/nswdpc/silverstripe-content-boilerplate/tree/master/_config) will be applied.

The configuration provided is based on the most common set of usage scenarios we've seen over the years. You can override this in your own project using the usual Silverstripe method. Here's an example:

```yaml
---
Name: my-app-content-userforms
After:
  - '#nswdpc-content-userforms'
---
SilverStripe\UserForms\Model\UserDefinedForm:
  block_default_userforms_css: false
```

Hope that answers your question.

Thanks
James
